# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41e2c857ed54afbaa283458f361d70cd21c327018422194359abe2ff4cc5691191c2ba72aa63740a9dc2686c23cd4018f587f56181a35fca14e256e91a252309

test:
  secret_key_base: 06b209a2662a201d0ff121a6ba37f7954bbaeeedc362ed0cbfd339fd8603373a04a8aa7c8d36f1393b70d2dc9d0c1303aa7e37da6cad749df34db3f727cccd3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
